api:
  fromEmail: "vetlog@josdem.io"
  callbackUrl: "https://gmailer.josdem.io/Callback"
  tokenPath: "/home/josdem/.gmailer/tokens"
server:
    port: 8083
app:
  version: ${version}

mail:
  username: test@example.com
  password: securepassword
  host: smtp.example.com
  port: 587
